name: NuGet Publish

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Install Dependencies
      timeout-minutes: 10
      uses: "./.github/steps/install_dependencies"

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Set VERSION variable from tag
      run: |
          $VERSION = "${{ github.ref }}" -replace 'refs/tags/v', ''
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: pwsh # Use PowerShell for better string handling
    #  run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Set VERSION variable from tag
      shell: cmd
      run: echo "VERSION2=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Debug VERSION
      run: echo "Version is ${{ env.VERSION }}"

    - name: Debug VERSION2
      run: echo "Version is ${VERSION2}, Version2 is ${VERSION}"

    - name: Build SimpleShimmer
      run: msbuild ./SimpleShimmer.csproj /r /property:Configuration=Release

    - name: Test
      run: dotnet test --configuration Release --runtime win-x64 --no-build

    - name: Pack
      run: dotnet pack --configuration Release --runtime win-x64 /p:Version=${{ env.VERSION }} --no-build --output .

    #- name: Pack
    #  shell: pwsh
    #  run: msbuild ./SimpleShimmer.csproj /t:pack /property:Configuration=Release

    - name: Push to NuGet
      run: dotnet nuget push SimpleShimmer.${{ env.VERSION }}.nupkg --api-key ${{ secrets.Nu_Key }} --source https://api.nuget.org/v3/index.json 

    - name: Push
      run: dotnet nuget push SimpleShimmer.${{ env.VERSION }}.nupkg --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/mou-haz/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GithubPackages_Key }}