name: NuGet Publish

on:
  push:
    branches: main/**

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Install Dependencies
      timeout-minutes: 10
      uses: "./.github/steps/install_dependencies"

    - name: Set VERSION variable from tag
      run: |
          $VERSION = "${{ github.ref }}" -replace 'refs/tags/v', ''
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: pwsh # Use PowerShell for better string handling
    #  run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
  
    - name: Get Previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.GithubPackages_Key }}
        
    - name: Get next version
      id: next
      uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

     - name: 'Get next minor version'
      id: next
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: New VERSION
      run: echo "New Version is ${{ steps.next.outputs.patch }}"

    - name: Build SimpleShimmer
      run: dotnet build --configuration Release --runtime win-x64

    - name: Test
      run: dotnet test --configuration Release --runtime win-x64 --no-build

    - name: Pack
      run: dotnet pack --configuration Release --runtime win-x64 /p:Version=${{ steps.next.outputs.patch }} --no-build --output .

    #- name: Pack
    #  shell: pwsh
    #  run: msbuild ./SimpleShimmer.csproj /t:pack /property:Configuration=Release

    - name: Push to NuGet
      run: dotnet nuget push SimpleShimmer.${{ steps.next.outputs.patch }}.nupkg --api-key ${{ secrets.Nu_Key }} --source https://api.nuget.org/v3/index.json 

    - name: Push
      run: dotnet nuget push SimpleShimmer.${{ steps.next.outputs.patch }}.nupkg --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/mou-haz/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GithubPackages_Key }}