name: NuGet Publish

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Install Dependencies
      timeout-minutes: 10
      uses: "./.github/steps/install_dependencies"

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Build SimpleShimmer
      shell: pwsh
      run: msbuild ./SimpleShimmer.csproj /r /property:Configuration=Release

    - name: Build
      run: dotnet build --configuration Release --runtime win-x64 /p:Version=${VERSION} /p:AssemblyVersion=${VERSION} /p:NuGetVersion=${VERSION}

    - name: Test
      run: dotnet test --configuration Release --runtime win-x64 /p:Version=${VERSION} /p:AssemblyVersion=${VERSION} /p:NuGetVersion=${VERSION} --no-build

    - name: Pack
      run: dotnet pack --configuration Release --runtime win-x64 /p:Version=${VERSION} /p:AssemblyVersion=${VERSION} /p:NuGetVersion=${VERSION} --no-build --output .

    - name: Push
      run: dotnet nuget push SimpleShimmer.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.Nu_Key }}

    - name: Push to GithubPackages
      run: dotnet nuget add source --username mou-haz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mou-haz/index.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GithubPackages_Key }}

    - name: Push
      run: dotnet nuget push SimpleShimmer.${VERSION}.nupkg --source https://nuget.pkg.github.com/mou-haz/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GithubPackages_Key }}